import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { ReactNode } from "react";
import { Footer } from "@/components/footer";
import { PromotionalBanner } from "@/components/promotionalBanner";
import { CartCountProvider } from "@/lib/cartCountContext";
import { getCart } from "@/lib/cartActions";
import { Toaster } from "@/components/ui/sonner";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const cart = await getCart();
  const initialCartCount = cart?.totalItems ?? 0;

  return (
    <html
      lang="en"
      className={`${roboto.variable} ${robotoMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartCountProvider initialCount={initialCartCount}>
          <Header />
          <PromotionalBanner />
          <main className="flex-1 mx-auto w-full max-w-360 px-4 sm:px-6 lg:px-8">
            {children}
          </main>
          <Toaster />
          <Footer />
        </CartCountProvider>
      </body>
    </html>
  );
}
